package main;

import com.formdev.flatlaf.FlatIntelliJLaf;
import config.MySQLConnection;
import frames.DataBarang;
import frames.PBFDistributor;
import frames.Pembelian;
import frames.Penjualan;
import java.awt.HeadlessException;
import java.beans.PropertyVetoException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import org.mindrot.BCrypt;

/**
 *
 * @author ZAFL
 */
public class Main extends javax.swing.JFrame {

  Connection conn = (Connection) MySQLConnection.connectDB();
  Boolean isLoggedIn = false;

  /**
   * Creates new form Main
   */
  public Main() {
    initComponents();
    menuLaporanBli.setVisible(false);
    setExtendedState(Main.MAXIMIZED_BOTH);
    menuState();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    dialogLogin = new javax.swing.JDialog();
    labelUsername = new javax.swing.JLabel();
    labelPassword = new javax.swing.JLabel();
    txtFldUsername = new javax.swing.JTextField();
    passFldPassword = new javax.swing.JPasswordField();
    btnLogin = new javax.swing.JButton();
    labelTitle = new javax.swing.JLabel();
    desktopPane = new javax.swing.JDesktopPane();
    menuBar = new javax.swing.JMenuBar();
    menuMain = new javax.swing.JMenu();
    menuItmBeranda = new javax.swing.JMenuItem();
    menuItmAuth = new javax.swing.JMenuItem();
    menuItmExit = new javax.swing.JMenuItem();
    menuData = new javax.swing.JMenu();
    menuItmBarang = new javax.swing.JMenuItem();
    menuItmPbf = new javax.swing.JMenuItem();
    menuTransaksi = new javax.swing.JMenu();
    menuPembelian = new javax.swing.JMenu();
    menuItmBeli = new javax.swing.JMenuItem();
    menuLaporanBli = new javax.swing.JMenu();
    menuItmLapBeli = new javax.swing.JMenuItem();
    menuPenjualan = new javax.swing.JMenu();
    menuItmJual = new javax.swing.JMenuItem();

    dialogLogin.setTitle("Login");
    dialogLogin.setMinimumSize(new java.awt.Dimension(430, 290));
    dialogLogin.setResizable(false);
    dialogLogin.setSize(new java.awt.Dimension(430, 310));

    labelUsername.setText("Username");

    labelPassword.setText("Password");

    txtFldUsername.setText("admin");

    passFldPassword.setText("BioApo");

    btnLogin.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
    btnLogin.setText("Login");
    btnLogin.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnLoginActionPerformed(evt);
      }
    });

    labelTitle.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
    labelTitle.setText("Login User");

    javax.swing.GroupLayout dialogLoginLayout = new javax.swing.GroupLayout(dialogLogin.getContentPane());
    dialogLogin.getContentPane().setLayout(dialogLoginLayout);
    dialogLoginLayout.setHorizontalGroup(
      dialogLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(dialogLoginLayout.createSequentialGroup()
        .addContainerGap(68, Short.MAX_VALUE)
        .addGroup(dialogLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelUsername)
            .addGroup(dialogLoginLayout.createSequentialGroup()
              .addComponent(labelPassword)
              .addGap(28, 28, 28)
              .addComponent(passFldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
          .addComponent(txtFldUsername, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(69, Short.MAX_VALUE))
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogLoginLayout.createSequentialGroup()
        .addGap(0, 0, Short.MAX_VALUE)
        .addComponent(labelTitle)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogLoginLayout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    dialogLoginLayout.setVerticalGroup(
      dialogLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogLoginLayout.createSequentialGroup()
        .addGap(20, 20, 20)
        .addComponent(labelTitle)
        .addGap(35, 35, 35)
        .addGroup(dialogLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(labelUsername)
          .addComponent(txtFldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(32, 32, 32)
        .addGroup(dialogLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(labelPassword)
          .addComponent(passFldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(33, 33, 33)
        .addComponent(btnLogin)
        .addContainerGap(81, Short.MAX_VALUE))
    );

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Apotek Biomedika");
    setBackground(new java.awt.Color(153, 153, 255));
    setMinimumSize(new java.awt.Dimension(960, 540));

    javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
    desktopPane.setLayout(desktopPaneLayout);
    desktopPaneLayout.setHorizontalGroup(
      desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 1280, Short.MAX_VALUE)
    );
    desktopPaneLayout.setVerticalGroup(
      desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 690, Short.MAX_VALUE)
    );

    menuBar.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
    menuBar.setPreferredSize(new java.awt.Dimension(220, 30));

    menuMain.setText("Main Menu");

    menuItmBeranda.setText("Beranda");
    menuMain.add(menuItmBeranda);

    menuItmAuth.setLabel("Login");
    menuItmAuth.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        menuItmAuthActionPerformed(evt);
      }
    });
    menuMain.add(menuItmAuth);

    menuItmExit.setText("Exit");
    menuItmExit.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        menuItmExitActionPerformed(evt);
      }
    });
    menuMain.add(menuItmExit);

    menuBar.add(menuMain);

    menuData.setText("Master Data");

    menuItmBarang.setText("Data Barang");
    menuItmBarang.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        menuItmBarangActionPerformed(evt);
      }
    });
    menuData.add(menuItmBarang);

    menuItmPbf.setText("PBF Distributor");
    menuItmPbf.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        menuItmPbfActionPerformed(evt);
      }
    });
    menuData.add(menuItmPbf);

    menuBar.add(menuData);

    menuTransaksi.setText("Transaksi");

    menuPembelian.setText("Pembelian");

    menuItmBeli.setText("Beli");
    menuItmBeli.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        menuItmBeliActionPerformed(evt);
      }
    });
    menuPembelian.add(menuItmBeli);

    menuLaporanBli.setText("Laporan");

    menuItmLapBeli.setText("Laporan Pembelian");
    menuLaporanBli.add(menuItmLapBeli);

    menuPembelian.add(menuLaporanBli);

    menuTransaksi.add(menuPembelian);

    menuPenjualan.setText("Penjualan");

    menuItmJual.setText("Jual");
    menuItmJual.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        menuItmJualActionPerformed(evt);
      }
    });
    menuPenjualan.add(menuItmJual);

    menuTransaksi.add(menuPenjualan);

    menuBar.add(menuTransaksi);

    setJMenuBar(menuBar);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(desktopPane)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(desktopPane)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void menuItmAuthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItmAuthActionPerformed
    if (menuItmAuth.getText().equals("Login")) {
      dialogLogin.setLocationRelativeTo(null);
      dialogLogin.setVisible(true);
    } else {
      isLoggedIn = false;
      menuState();
    }
  }//GEN-LAST:event_menuItmAuthActionPerformed

  private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
    if (txtFldUsername.getText().isEmpty()) {
      txtFldUsername.requestFocus();
    }
    if (passFldPassword.getPassword().length == 0) {
      passFldPassword.requestFocus();
    }
    if (!txtFldUsername.getText().isEmpty() && passFldPassword.getPassword().length > 0) {
      String username = txtFldUsername.getText();
      String password = String.valueOf(passFldPassword.getPassword());

      String query = "SELECT `password` FROM `data_user` WHERE `nama`='" + username + "'";
      try {
        Statement stm = conn.createStatement();
        ResultSet rs = stm.executeQuery(query);

        if (rs.next()) {
          String getPassword = rs.getString("password");

          if (BCrypt.checkpw(password, getPassword)) {
            dialogLogin.setVisible(false);
            dialogLogin.dispose();

            isLoggedIn = true;
            menuState();
          } else {
            JOptionPane.showMessageDialog(null, "Password salah!");
          }
        } else {
          JOptionPane.showMessageDialog(null, "Password salah!");
        }
      } catch (HeadlessException | SQLException e) {
        System.err.println(e.getMessage());
      }
    }
  }//GEN-LAST:event_btnLoginActionPerformed

  private void menuItmExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItmExitActionPerformed
    System.exit(0);
  }//GEN-LAST:event_menuItmExitActionPerformed

  private void menuItmBeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItmBeliActionPerformed
    Pembelian pembelian = new Pembelian();
    if (desktopPane.getAllFrames().length > 0) {
      desktopPane.remove(0);
    }
    desktopPane.add(pembelian);
    try {
      pembelian.setMaximum(true);
    } catch (PropertyVetoException pve) {
      System.err.println(pve.getMessage());
    }
    pembelian.setVisible(true);
    pembelian.toFront();
  }//GEN-LAST:event_menuItmBeliActionPerformed

  private void menuItmBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItmBarangActionPerformed
    DataBarang dataBarang = new DataBarang();
    if (desktopPane.getAllFrames().length > 0) {
      desktopPane.remove(0);
    }
    desktopPane.add(dataBarang);
    try {
      dataBarang.setMaximum(true);
    } catch (PropertyVetoException pve) {
      System.err.println(pve.getMessage());
    }
    dataBarang.setVisible(true);
    dataBarang.toFront();
  }//GEN-LAST:event_menuItmBarangActionPerformed

  private void menuItmPbfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItmPbfActionPerformed
    PBFDistributor distributor = new PBFDistributor();
    if (desktopPane.getAllFrames().length > 0) {
      desktopPane.remove(0);
    }
    desktopPane.add(distributor);
    try {
      distributor.setMaximum(true);
    } catch (PropertyVetoException pve) {
      System.err.println(pve.getMessage());
    }
    distributor.setVisible(true);
    distributor.toFront();
  }//GEN-LAST:event_menuItmPbfActionPerformed

  private void menuItmJualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItmJualActionPerformed
    Penjualan penjualan = new Penjualan();
    if (desktopPane.getAllFrames().length > 0) {
      desktopPane.remove(0);
    }
    desktopPane.add(penjualan);
    try {
      penjualan.setMaximum(true);
    } catch (PropertyVetoException pve) {
      System.err.println(pve.getMessage());
    }
    penjualan.setVisible(true);
    penjualan.toFront();
  }//GEN-LAST:event_menuItmJualActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    try {
      UIManager.setLookAndFeel(new FlatIntelliJLaf());
      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
          new Main().setVisible(true);
        }
      });
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnLogin;
  public javax.swing.JDesktopPane desktopPane;
  private javax.swing.JDialog dialogLogin;
  private javax.swing.JLabel labelPassword;
  private javax.swing.JLabel labelTitle;
  private javax.swing.JLabel labelUsername;
  private javax.swing.JMenuBar menuBar;
  private javax.swing.JMenu menuData;
  private javax.swing.JMenuItem menuItmAuth;
  private javax.swing.JMenuItem menuItmBarang;
  private javax.swing.JMenuItem menuItmBeli;
  private javax.swing.JMenuItem menuItmBeranda;
  private javax.swing.JMenuItem menuItmExit;
  private javax.swing.JMenuItem menuItmJual;
  private javax.swing.JMenuItem menuItmLapBeli;
  private javax.swing.JMenuItem menuItmPbf;
  private javax.swing.JMenu menuLaporanBli;
  private javax.swing.JMenu menuMain;
  private javax.swing.JMenu menuPembelian;
  private javax.swing.JMenu menuPenjualan;
  private javax.swing.JMenu menuTransaksi;
  private javax.swing.JPasswordField passFldPassword;
  private javax.swing.JTextField txtFldUsername;
  // End of variables declaration//GEN-END:variables

  private void menuState() {
    if (!isLoggedIn) {
      menuItmAuth.setText("Login");
      menuItmBeranda.setEnabled(false);
      menuData.setEnabled(false);
      menuTransaksi.setEnabled(false);
    } else {
      menuItmAuth.setText("Logout");
      menuItmBeranda.setEnabled(true);
      menuData.setEnabled(true);
      menuTransaksi.setEnabled(true);
    }
  }
}
