package utility;

import java.awt.Color;
import java.awt.Component;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 *
 * @author ZAFL
 */
public class ItemPencarian extends javax.swing.JPanel {
  
  private ActionListener eventClick;
  
  public ItemPencarian(DataPencarian data) {
    initComponents();
    setData(data);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    lbText = new javax.swing.JLabel();

    setBackground(new java.awt.Color(255, 255, 255));

    lbText.setText("Text...");
    lbText.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        lbTextMouseClicked(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(lbText, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(lbText, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
    );
  }// </editor-fold>//GEN-END:initComponents

  private void lbTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbTextMouseClicked
    eventClick.actionPerformed(null);
  }//GEN-LAST:event_lbTextMouseClicked


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel lbText;
  // End of variables declaration//GEN-END:variables

  private void setData(DataPencarian data) {
    addEventMouse(this);
    addEventMouse(lbText);
    lbText.setText(data.getText());
  }

  private void addEventMouse(Component component) {
    component.addMouseListener(new MouseAdapter() {
      @Override
      public void mouseEntered(MouseEvent e) {
        setBackground(new Color(216, 216, 216));
      }

      @Override
      public void mouseExited(MouseEvent e) {
        setBackground(Color.white);
      }

    });
  }
  
  public void addEvent(ActionListener eventClick) {
    this.eventClick = eventClick;
  }
}
