package utility;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import net.miginfocom.swing.MigLayout;

/**
 *
 * @author ZAFL
 */
public class PanelPencarian extends javax.swing.JPanel {

  private EventClick event;

  public void addEventClick(EventClick event) {
    this.event = event;
  }
 
  public PanelPencarian() {
    initComponents();
    setLayout(new MigLayout("fillx", "0[]0", "0[]0"));
  }

  public void setData(List<DataPencarian> data) {
    this.removeAll();
    for (DataPencarian d : data) {
      ItemPencarian item = new ItemPencarian(d);
      item.addEvent(new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
          event.itemClick(d);
        }
      });
      this.add(item, "wrap");
    }
    repaint();
    revalidate();
  }

  public int getItemSize() {
    return getComponentCount();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 500, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 0, Short.MAX_VALUE)
    );
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  // End of variables declaration//GEN-END:variables
}
